external-secrets:

  bitwarden-sdk-server:
    enabled: true
    image:
      tls:
        enabled: true
        volumeMounts:
          - mountPath: "/certs"
            name: "bitwarden-tls-certs"
        volumes:
          - name: "bitwarden-tls-certs"
            secret:
              secretName: "bitwarden-tls-certs"
              items:
                - key: "tls.crt"
                  path: "cert.pem"
                - key: "tls.key"
                  path: "key.pem"
                - key: "ca.crt"
                  path: "ca.pem"
    podDnsConfig:
      options:
        - name: ndots
          value: "2"
    podAnnotations:
        secret.reloader.stakater.com/reload: "bitwarden-css-certs,bitwarden-secrets-manager,bitwarden-secrets-manager-secrets,bitwarden-tls-certs,bitwarden-access-token"
